spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///config-repo
        git:
          uri: file:///config-repo
          skip-ssl-validation: true
          clone-on-start: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.springframework.cloud.config: WARN